project:
  type: website
  output-dir: docs

website:
  title: "Twitter Analysis Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - rocket_league.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

