project:
  type: website
  output-dir: docs

website:
  title: "Twitter Analysis Project"
  navbar:
    left:
      - href: index.qmd
      - tweet_scrape.qmd
      - database.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

