project:
  type: website
  output-dir: docs

website:
  title: "Twitter Analysis Project"
  navbar:
    left:
      - patchwork.qmd
      - wordpatchwork.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

