project:
  type: website
  output-dir: docs

website:
  title: "Twitter Analysis Project"
  navbar:
    left:
      
      - rocket_league.qmd
      - pogo.qmd
      - rstats.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

